// 旅行足迹数据
const travelSpots = [
  {
    title: '北京 · 中国',
    position: { lat: 39.9042, lng: 116.4074 },
    diaryFiles: ['diary/beijing-1.md', 'diary/beijing-2.md'],
    photos: ['assets/images/beijing-1.jpg', 'assets/images/beijing-2.jpg'],
  },
  {
    title: '天津 · 中国',
    position: { lat: 39.3434, lng: 117.3616 },
    diaryFiles: ['diary/tianjin.md'],
    photos: ['assets/images/tianjin.jpg'],
  },
  {
    title: '青岛 · 中国',
    position: { lat: 36.0671, lng: 120.3826 },
    diaryFiles: ['diary/qingdao.md'],
    photos: ['assets/images/qingdao.jpg'],
  },
  {
    title: '香港 · 中国',
    position: { lat: 22.3193, lng: 114.1694 },
    diaryFiles: ['diary/hongkong-1.md','diary/hongkong-2.md'],
    photos: ['assets/images/hongkong-1.jpg','assets/images/hongkong-2.jpg'],
  },
  {
    title: '三亚 · 中国',
    position: { lat: 18.2528, lng: 109.5119 },
    diaryFiles: ['diary/sanya.md'],
    photos: ['assets/images/sanya.jpg'],
  },
  {
    title: '齐齐哈尔 · 中国',
    position: { lat: 47.3543, lng: 123.9175 },
    diaryFiles: ['diary/qiqihar.md'],
    photos: ['assets/images/qiqihar.jpg'],
  },
  {
    title: '巴黎 · 法国',
    position: { lat: 48.8566, lng: 2.3522 },
    diaryFiles: ['diary/paris.md'],
    photos: ['assets/images/zw.jpg'],
  },
  {
    title: '伦敦 · 英国',
    position: { lat: 51.5074, lng: -0.1278 },
    diaryFiles: ['diary/london.md'],
    photos: ['assets/images/london.jpg'],
  },
  {
    title: '爱丁堡 · 英国',
    position: { lat: 55.9533, lng: -3.1883 },
    diaryFiles: ['diary/edinburgh.md'],
    photos: ['assets/images/edinburgh.jpg'],
  },
  {
    title: '瑞士少女峰 · 瑞士',
    position: { lat: 46.537, lng: 7.961 },
    diaryFiles: ['diary/jungfrau.md'],
    photos: ['assets/images/zw.jpg'],
  },
  {
    title: '采尔马特 · 瑞士',
    position: { lat: 46.0207, lng: 7.7491 },
    diaryFiles: ['diary/zermatt.md'],
    photos: ['assets/images/zw.jpg'],
  },
  {
    title: '费城 · 美国',
    position: { lat: 39.9526, lng: -75.1652 },
    diaryFiles: ['diary/philadelphia.md'],
    photos: ['assets/images/philadelphia.jpg'],
  },
  {
    title: '纽约 · 美国',
    position: { lat: 40.7128, lng: -74.006 },
    diaryFiles: ['diary/newyork.md'],
    photos: ['assets/images/newyork.jpg'],
  },
  {
    title: '奥兰多 · 美国',
    position: { lat: 28.5383, lng: -81.3792 },
    diaryFiles: ['diary/orlando-1.md','diary/orlando-2.md','diary/orlando-3.md'],
    photos: ['assets/images/orlando-1.jpg','assets/images/orlando-2.jpg','assets/images/orlando-3.jpg'],
  },
  {
    title: '华盛顿 · 美国',
    position: { lat: 38.9072, lng: -77.0369 },
    diaryFiles: ['diary/washington-1.md','diary/washington-2.md'],
    photos: ['assets/images/washington-1.jpg','assets/images/washington-2.jpg'],
  },
  {
    title: '旧金山 · 美国',
    position: { lat: 37.7749, lng: -122.4194 },
    diaryFiles: ['diary/sanfrancisco.md'],
    photos: ['assets/images/sanfrancisco.jpg'],
  },
  {
    title: '洛杉矶 · 美国',
    position: { lat: 34.0522, lng: -118.2437 },
    diaryFiles: ['diary/losangeles-1.md','diary/losangeles-2.md'],
    photos: ['assets/images/losangeles-1.jpg','assets/images/losangeles-2.jpg'],
  },
  {
    title: '滑铁卢 · 加拿大',
    position: { lat: 43.4643, lng: -80.5204 },
    diaryFiles: ['diary/waterloo-1.md','diary/waterloo-2.md'],
    photos: ['assets/images/waterloo-1.jpg','assets/images/waterloo-2.jpg'],
  },
  {
    title: '多伦多 · 加拿大',
    position: { lat: 43.6532, lng: -79.3832 },
    diaryFiles: ['diary/toronto-1.md','diary/toronto-2.md'],
    photos: ['assets/images/toronto-1.jpg','assets/images/toronto-2.jpg'],
  },
  {
    title: '蒙特利尔 · 加拿大',
    position: { lat: 45.5017, lng: -73.5673 },
    diaryFiles: ['diary/montreal.md'],
    photos: ['assets/images/montreal.jpg'],
  },
  {
    title: '波多黎各 · 美国',
    position: { lat: 18.2208, lng: -66.5901 },
    diaryFiles: ['diary/puertorico.md'],
    photos: ['assets/images/puertorico.jpg'],
  },
  {
  title: '丹佛 · 美国',
  position: { lat: 39.7392, lng: -104.9903 },
  diaryFiles: ['diary/denver-1.md','diary/denver-2.md'],
  photos: ['assets/images/denver-1.jpg','assets/images/denver-2.jpg'],
  },
  {
  title: '巴斯 · 英国',
  position: { lat: 51.3811, lng: -2.3590 },
  diaryFiles: ['diary/bath.md'],
  photos: ['assets/images/bath.jpg'],
  },
  {
  title: '普林斯顿 · 美国',
  position: { lat: 40.3573, lng: -74.6672 },
  diaryFiles: ['diary/princeton.md'],
  photos: ['assets/images/princeton.jpg'],
  },
  {
  title: '蒙特利尔 · 加拿大',
  position: { lat: 45.5019, lng: -73.5674 },
  diaryFiles: ['diary/montreal.md'],
  photos: ['assets/images/montreal.jpg'],
  },
  {
  title: '波士顿 · 美国',
  position: { lat: 42.3601, lng: -71.0589 },
  diaryFiles: ['diary/boston.md'],
  photos: ['assets/images/boston.jpg'],
  },
  {
  title: '上海 · 中国',
  position: { lat: 31.2304, lng: 121.4737 },
  diaryFiles: ['diary/shanghai.md'],
  photos: ['assets/images/shanghai.jpg'],
  },
  {
  title: '武汉 · 中国',
  position: { lat: 30.5928, lng: 114.3055 },
  diaryFiles: ['diary/wuhan.md'],
  photos: ['assets/images/wuhan.jpg'],
  },
  {
  title: '黄石国家公园 · 美国',
  position: { lat: 44.4280, lng: -110.5885 },
  diaryFiles: ['diary/yellowstone.md'],
  photos: ['assets/images/yellowstone.jpg'],
  },
  {
  title: '巴塞罗那 · 西班牙',
  position: { lat: 41.3851, lng: 2.1734 },
  diaryFiles: ['diary/barcelona.md'],
  photos: ['assets/images/zw.jpg'],
  },


];
